### ISSUE TITLE
query doesn't return a pandas dataframe

### ISSUE THREAD

**Issue by drthornt** [dcoles/prometheus-pandas#7]
I tried an example and expected to get back a pandas dataframe that I could join with other data. I was unable to do that .

```
>python3
Python 3.10.13 (main, Oct 20 2023, 13:56:06) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_pandas import query
>>> p = query.Prometheus('http://localhost:8080')
>>> print(p.query_range('sum(rate(node_cpu_seconds_total{mode=~"system|user"}[1m])) by (mode)','2024-09-12T00:00:00Z', '2024-09-12T06:00:00Z', '1h'))
                     {mode="system"}  {mode="user"}
2024-09-12 00:00:00         1.643997       4.238185
2024-09-12 01:00:00         2.701799      13.664999
2024-09-12 02:00:00         2.268798       9.020798
2024-09-12 03:00:00         2.123197       8.606198
2024-09-12 04:00:00         2.430808      10.202453
2024-09-12 05:00:00         2.196602      11.365402
2024-09-12 06:00:00         2.222159      10.895345
>>> type(p)
<class 'prometheus_pandas.query.Prometheus'>
>>> mydf = p.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Prometheus' object has no attribute 'to_pandas'
>>> p.info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Prometheus' object has no attribute 'info'
>>> p.head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Prometheus' object has no attribute 'head'
>>> deep = p.copy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Prometheus' object has no attribute 'copy'
>>> 

```

**Comment by dcoles** [comment]
Hi @drthornt.

In this case the dataframe is returned as the result of the `query_range` method rather than as the `Prometheus` object itself:

```
>>> p = query.Prometheus('http://localhost:9090')
>>> mydf = p.query_range('sum(rate(node_cpu_seconds_total{mode=~"system|user"}[1m])) by (mode)','2024-09-12T00:00:00Z', '2024-09-12T06:00:00Z', '1h')
>>> mydf.info()
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7 entries, 2024-09-12 00:00:00 to 2024-09-12 06:00:00
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   {mode="system"}  7 non-null      float64
 1   {mode="user"}    7 non-null      float64
dtypes: float64(2)
memory usage: 168.0 bytes
>>> mydf.head()
                     {mode="system"}  {mode="user"}
2024-09-12 00:00:00         0.005111       0.008222
2024-09-12 01:00:00         0.004222       0.008222
2024-09-12 02:00:00         0.005556       0.008000
2024-09-12 03:00:00         0.003778       0.005333
2024-09-12 04:00:00         0.002889       0.005111
```

I'll update the example in the README to make that a bit more clear.

**Comment by drthornt** [comment]
ace!
that worked.
thank you.

**Comment by dcoles** [comment]
No worries! Glad it's working!
